-sudo: true		
 -dist: trusty		
  language: java		  language: java
  jdk: 		  jdk: 
    - oraclejdk8		    - oraclejdk8
 -		
 -jobs:		
 -  include:		
 -    - stage: compile jar		
 -      before_script:		
 -        - chmod +x gradle/wrapper/gradle-wrapper.jar		
 -      script:		
 -        - ./gradlew build
 -    - stage: test		
 -    		
 -    - stage: build docker image
    
