sudo: true
dist: trusty
language: java

jdk:
 - oraclejdk8

jobs:
  include:
  - stage: compile jar
    before_install:
     - chmod +x gradlew
    script:
     - ./gradlew assemble
  - stage: test
  - stage: build docker image

